# Generated by Django 5.2 on 2025-05-14 14:03

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категории книг',
                'verbose_name_plural': 'Категории книг',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='books/', verbose_name='Файл книги (.pdf)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/cover-image/', verbose_name='Обложка книги')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('pages', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Количество страниц')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Год')),
                ('category', models.ManyToManyField(related_name='books', to='books.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
