# Generated by Django 5.2 on 2025-04-30 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(max_length=25, validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Год'),
        ),
    ]
