# Generated by Django 5.2 on 2025-04-30 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_pages_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(max_length=4, validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Год'),
        ),
    ]
