# Generated by Django 5.2 on 2025-05-01 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Год'),
        ),
    ]
