# Generated by Django 5.2 on 2025-05-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='phone1',
            new_name='phone',
        ),
    ]
