# Generated by Django 5.2 on 2025-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Лого')),
                ('phone1', models.CharField(help_text='Вы можете начать номер телефона с +996 (700) 700 700', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('map', models.TextField(null=True, verbose_name='карта')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
