# Generated by Django 5.2 on 2025-05-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_sociallink_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(help_text='CSS-класс иконки Bootstrap, пример: bi bi-twitter, bi bi-instagram', max_length=100, verbose_name='Иконка'),
        ),
    ]
